#!/usr/bin/env bash

# using ssh to connect to a server

ssh ubuntu -i ~/.ssh/school

# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu

ssh ubuntu@100.26.253.17 -i ~/.ssh/school


ssh ubuntu -i ~/.ssh/school
